/**
 * Provides a gRPC server that defines an interface for modifying the behavior of the simulation. The code
 * in this package references Java code that is generated by the protobuf compiler. The protobuf compiler is
 * integrated into the Maven build process and generates Java code in the target directory. The code in this
 * package then calls the generated code.
 * </p>
 * The following classes comprise the package:
 * <ol>
 * <li>{@link org.ericace.grpcserver.NBodyServiceServer} - Starts a gRPC server on a defined port that responds to
 * gRPC calls.
 * </ol>
 */
package org.ericace.grpcserver;