/**
 * Provides a gRPC server that defines an interface for modifying the behavior of the simulation while it
 * is running. The code in this package references Java code that is generated by the protobuf compiler.
 * The protobuf compiler is integrated into the Maven build process and generates Java code as part of the Maven
 * build. The code in this package then calls the generated code. See the {@code grpc} module for more info.
 */
package org.ericace.grpcserver;