/**
 * Provides a gRPC server that defines an interface for modifying the behavior of the simulation. The code
 * in this package references Java code that is generated by the protobuf compiler. The protobuf compiler is
 * integrated into the Maven build process and generates Java code in the target directory. The code in this
 * package then calls the generated code.
 */
package org.ericace.grpcserver;