{
 "title": "N-Body Simulation",
 "description": "Metrics for the n-body Java simulation",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "N-Body Computations/sec",
   "type": "graph",
   "description": "N-Body computations per second (generally bodies * bodies-1)",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "irate(nbody_computations[1m])" }
   ]
  },
  {
   "title": "Sim Cycles per second",
   "type": "graph",
   "description": "Shows the number of times each second that the Computation Runner and JME threads complete one compute cycle",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(nbody_computation_count[1m])"
    }
   ]
  },
  {
   "title": "Result Queue Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nbody_result_queue_size" }
   ]
  },
  {
   "title": "Simulation Bodies",
   "type": "graph",
   "description": "The number of bodies computed and rendered on each render cycle",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nbody_body_count_gauge" }
   ]
  },
  {
   "title": "Computation Threads",
   "type": "gauge",
   "description": "Number of threads in the Computation Runner thread pool",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "targets": [
    { "expr": "nbody_computation_thread_gauge" }
   ]
  },
  {
   "title": "Max Result Queues",
   "type": "singlestat",
   "description": "The maximum number of result queues to hold computation results for the render thread",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "nbody_result_queue_max_size" }
   ]
  },
  {
   "title": "No Queues for Computation Runner",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nbody_no_computation_queues_count[10s  ])"
    }
   ]
  },
  {
   "title": "Render Thread Starved",
   "type": "graph",
   "description": "The number of times the render thread does not have a queue to render",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(nbody_no_queues_to_render_count[1m])"
    }
   ]
  },
  {
   "title": "JVM Memory Bytes Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_memory_bytes_used" }
   ]
  },
  {
   "title": "JVM Garbage Collection Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum[5m])"
    }
   ]
  }
 ]
}