#!/usr/bin/env bash

docker run -d --rm \
 -p 9090:9090 \
 --name=prometheus \
 --net="host" \
 --mount 'type=bind,source=/home/eace/IdeaProjects/nbodyjava/src/main/resources/prometheus/prometheus.yml,target=/etc/prometheus' \
 prom/prometheus

docker run -d --rm \
 -p 3000:3000 \
 --name=grafana \
 --net="host" \
 -e "GF_SECURITY_ADMIN_USER=root" \
 -e "GF_SECURITY_ADMIN_PASSWORD=secret" \
 grafana/grafana
