// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nbodyservice.proto

package org.ericace.grpcserver;

public interface BodyDescriptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nbodyservice.BodyDescription)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional float x = 1;</code>
   */
  float getX();

  /**
   * <code>optional float y = 2;</code>
   */
  float getY();

  /**
   * <code>optional float z = 3;</code>
   */
  float getZ();

  /**
   * <code>optional float vx = 4;</code>
   */
  float getVx();

  /**
   * <code>optional float vy = 5;</code>
   */
  float getVy();

  /**
   * <code>optional float vz = 6;</code>
   */
  float getVz();

  /**
   * <code>optional float mass = 7;</code>
   */
  float getMass();

  /**
   * <code>optional float radius = 8;</code>
   */
  float getRadius();

  /**
   * <code>optional bool is_sun = 9;</code>
   */
  boolean getIsSun();

  /**
   * <code>optional .nbodyservice.CollisionBehaviorEnum collision_behavior = 10;</code>
   */
  int getCollisionBehaviorValue();
  /**
   * <code>optional .nbodyservice.CollisionBehaviorEnum collision_behavior = 10;</code>
   */
  org.ericace.grpcserver.CollisionBehaviorEnum getCollisionBehavior();

  /**
   * <code>optional .nbodyservice.BodyColorEnum body_color = 11;</code>
   */
  int getBodyColorValue();
  /**
   * <code>optional .nbodyservice.BodyColorEnum body_color = 11;</code>
   */
  org.ericace.grpcserver.BodyColorEnum getBodyColor();

  /**
   * <code>optional float frag_factor = 12;</code>
   */
  float getFragFactor();

  /**
   * <code>optional float frag_step = 13;</code>
   */
  float getFragStep();

  /**
   * <code>optional bool with_telemetry = 14;</code>
   */
  boolean getWithTelemetry();

  /**
   * <code>optional string name = 15;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 15;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string class = 16;</code>
   */
  java.lang.String getClass_();
  /**
   * <code>optional string class = 16;</code>
   */
  com.google.protobuf.ByteString
      getClass_Bytes();

  /**
   * <code>optional bool pinned = 17;</code>
   */
  boolean getPinned();
}
