// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nbodyservice.proto

package org.ericace.grpcserver;

/**
 * <pre>
 * All the params required to represent a body in the simulation
 * </pre>
 *
 * Protobuf type {@code nbodyservice.BodyDescription}
 */
public  final class BodyDescription extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:nbodyservice.BodyDescription)
    BodyDescriptionOrBuilder {
  // Use BodyDescription.newBuilder() to construct.
  private BodyDescription(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BodyDescription() {
    x_ = 0F;
    y_ = 0F;
    z_ = 0F;
    vx_ = 0F;
    vy_ = 0F;
    vz_ = 0F;
    mass_ = 0F;
    radius_ = 0F;
    isSun_ = false;
    collisionBehavior_ = 0;
    bodyColor_ = 0;
    fragFactor_ = 0F;
    fragStep_ = 0F;
    withTelemetry_ = false;
    name_ = "";
    class__ = "";
    pinned_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private BodyDescription(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 13: {

            x_ = input.readFloat();
            break;
          }
          case 21: {

            y_ = input.readFloat();
            break;
          }
          case 29: {

            z_ = input.readFloat();
            break;
          }
          case 37: {

            vx_ = input.readFloat();
            break;
          }
          case 45: {

            vy_ = input.readFloat();
            break;
          }
          case 53: {

            vz_ = input.readFloat();
            break;
          }
          case 61: {

            mass_ = input.readFloat();
            break;
          }
          case 69: {

            radius_ = input.readFloat();
            break;
          }
          case 72: {

            isSun_ = input.readBool();
            break;
          }
          case 80: {
            int rawValue = input.readEnum();

            collisionBehavior_ = rawValue;
            break;
          }
          case 88: {
            int rawValue = input.readEnum();

            bodyColor_ = rawValue;
            break;
          }
          case 101: {

            fragFactor_ = input.readFloat();
            break;
          }
          case 109: {

            fragStep_ = input.readFloat();
            break;
          }
          case 112: {

            withTelemetry_ = input.readBool();
            break;
          }
          case 122: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 130: {
            java.lang.String s = input.readStringRequireUtf8();

            class__ = s;
            break;
          }
          case 136: {

            pinned_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.ericace.grpcserver.Nbodyservice.internal_static_nbodyservice_BodyDescription_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.ericace.grpcserver.Nbodyservice.internal_static_nbodyservice_BodyDescription_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.ericace.grpcserver.BodyDescription.class, org.ericace.grpcserver.BodyDescription.Builder.class);
  }

  public static final int X_FIELD_NUMBER = 1;
  private float x_;
  /**
   * <code>optional float x = 1;</code>
   */
  public float getX() {
    return x_;
  }

  public static final int Y_FIELD_NUMBER = 2;
  private float y_;
  /**
   * <code>optional float y = 2;</code>
   */
  public float getY() {
    return y_;
  }

  public static final int Z_FIELD_NUMBER = 3;
  private float z_;
  /**
   * <code>optional float z = 3;</code>
   */
  public float getZ() {
    return z_;
  }

  public static final int VX_FIELD_NUMBER = 4;
  private float vx_;
  /**
   * <code>optional float vx = 4;</code>
   */
  public float getVx() {
    return vx_;
  }

  public static final int VY_FIELD_NUMBER = 5;
  private float vy_;
  /**
   * <code>optional float vy = 5;</code>
   */
  public float getVy() {
    return vy_;
  }

  public static final int VZ_FIELD_NUMBER = 6;
  private float vz_;
  /**
   * <code>optional float vz = 6;</code>
   */
  public float getVz() {
    return vz_;
  }

  public static final int MASS_FIELD_NUMBER = 7;
  private float mass_;
  /**
   * <code>optional float mass = 7;</code>
   */
  public float getMass() {
    return mass_;
  }

  public static final int RADIUS_FIELD_NUMBER = 8;
  private float radius_;
  /**
   * <code>optional float radius = 8;</code>
   */
  public float getRadius() {
    return radius_;
  }

  public static final int IS_SUN_FIELD_NUMBER = 9;
  private boolean isSun_;
  /**
   * <code>optional bool is_sun = 9;</code>
   */
  public boolean getIsSun() {
    return isSun_;
  }

  public static final int COLLISION_BEHAVIOR_FIELD_NUMBER = 10;
  private int collisionBehavior_;
  /**
   * <code>optional .nbodyservice.CollisionBehaviorEnum collision_behavior = 10;</code>
   */
  public int getCollisionBehaviorValue() {
    return collisionBehavior_;
  }
  /**
   * <code>optional .nbodyservice.CollisionBehaviorEnum collision_behavior = 10;</code>
   */
  public org.ericace.grpcserver.CollisionBehaviorEnum getCollisionBehavior() {
    org.ericace.grpcserver.CollisionBehaviorEnum result = org.ericace.grpcserver.CollisionBehaviorEnum.valueOf(collisionBehavior_);
    return result == null ? org.ericace.grpcserver.CollisionBehaviorEnum.UNRECOGNIZED : result;
  }

  public static final int BODY_COLOR_FIELD_NUMBER = 11;
  private int bodyColor_;
  /**
   * <code>optional .nbodyservice.BodyColorEnum body_color = 11;</code>
   */
  public int getBodyColorValue() {
    return bodyColor_;
  }
  /**
   * <code>optional .nbodyservice.BodyColorEnum body_color = 11;</code>
   */
  public org.ericace.grpcserver.BodyColorEnum getBodyColor() {
    org.ericace.grpcserver.BodyColorEnum result = org.ericace.grpcserver.BodyColorEnum.valueOf(bodyColor_);
    return result == null ? org.ericace.grpcserver.BodyColorEnum.UNRECOGNIZED : result;
  }

  public static final int FRAG_FACTOR_FIELD_NUMBER = 12;
  private float fragFactor_;
  /**
   * <code>optional float frag_factor = 12;</code>
   */
  public float getFragFactor() {
    return fragFactor_;
  }

  public static final int FRAG_STEP_FIELD_NUMBER = 13;
  private float fragStep_;
  /**
   * <code>optional float frag_step = 13;</code>
   */
  public float getFragStep() {
    return fragStep_;
  }

  public static final int WITH_TELEMETRY_FIELD_NUMBER = 14;
  private boolean withTelemetry_;
  /**
   * <code>optional bool with_telemetry = 14;</code>
   */
  public boolean getWithTelemetry() {
    return withTelemetry_;
  }

  public static final int NAME_FIELD_NUMBER = 15;
  private volatile java.lang.Object name_;
  /**
   * <code>optional string name = 15;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>optional string name = 15;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLASS_FIELD_NUMBER = 16;
  private volatile java.lang.Object class__;
  /**
   * <code>optional string class = 16;</code>
   */
  public java.lang.String getClass_() {
    java.lang.Object ref = class__;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      class__ = s;
      return s;
    }
  }
  /**
   * <code>optional string class = 16;</code>
   */
  public com.google.protobuf.ByteString
      getClass_Bytes() {
    java.lang.Object ref = class__;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      class__ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PINNED_FIELD_NUMBER = 17;
  private boolean pinned_;
  /**
   * <code>optional bool pinned = 17;</code>
   */
  public boolean getPinned() {
    return pinned_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (x_ != 0F) {
      output.writeFloat(1, x_);
    }
    if (y_ != 0F) {
      output.writeFloat(2, y_);
    }
    if (z_ != 0F) {
      output.writeFloat(3, z_);
    }
    if (vx_ != 0F) {
      output.writeFloat(4, vx_);
    }
    if (vy_ != 0F) {
      output.writeFloat(5, vy_);
    }
    if (vz_ != 0F) {
      output.writeFloat(6, vz_);
    }
    if (mass_ != 0F) {
      output.writeFloat(7, mass_);
    }
    if (radius_ != 0F) {
      output.writeFloat(8, radius_);
    }
    if (isSun_ != false) {
      output.writeBool(9, isSun_);
    }
    if (collisionBehavior_ != org.ericace.grpcserver.CollisionBehaviorEnum.UNDEF.getNumber()) {
      output.writeEnum(10, collisionBehavior_);
    }
    if (bodyColor_ != org.ericace.grpcserver.BodyColorEnum.NOCOLOR.getNumber()) {
      output.writeEnum(11, bodyColor_);
    }
    if (fragFactor_ != 0F) {
      output.writeFloat(12, fragFactor_);
    }
    if (fragStep_ != 0F) {
      output.writeFloat(13, fragStep_);
    }
    if (withTelemetry_ != false) {
      output.writeBool(14, withTelemetry_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, name_);
    }
    if (!getClass_Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 16, class__);
    }
    if (pinned_ != false) {
      output.writeBool(17, pinned_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (x_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, x_);
    }
    if (y_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, y_);
    }
    if (z_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, z_);
    }
    if (vx_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(4, vx_);
    }
    if (vy_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(5, vy_);
    }
    if (vz_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(6, vz_);
    }
    if (mass_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(7, mass_);
    }
    if (radius_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(8, radius_);
    }
    if (isSun_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(9, isSun_);
    }
    if (collisionBehavior_ != org.ericace.grpcserver.CollisionBehaviorEnum.UNDEF.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(10, collisionBehavior_);
    }
    if (bodyColor_ != org.ericace.grpcserver.BodyColorEnum.NOCOLOR.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(11, bodyColor_);
    }
    if (fragFactor_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(12, fragFactor_);
    }
    if (fragStep_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(13, fragStep_);
    }
    if (withTelemetry_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(14, withTelemetry_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, name_);
    }
    if (!getClass_Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, class__);
    }
    if (pinned_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(17, pinned_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.ericace.grpcserver.BodyDescription)) {
      return super.equals(obj);
    }
    org.ericace.grpcserver.BodyDescription other = (org.ericace.grpcserver.BodyDescription) obj;

    boolean result = true;
    result = result && (
        java.lang.Float.floatToIntBits(getX())
        == java.lang.Float.floatToIntBits(
            other.getX()));
    result = result && (
        java.lang.Float.floatToIntBits(getY())
        == java.lang.Float.floatToIntBits(
            other.getY()));
    result = result && (
        java.lang.Float.floatToIntBits(getZ())
        == java.lang.Float.floatToIntBits(
            other.getZ()));
    result = result && (
        java.lang.Float.floatToIntBits(getVx())
        == java.lang.Float.floatToIntBits(
            other.getVx()));
    result = result && (
        java.lang.Float.floatToIntBits(getVy())
        == java.lang.Float.floatToIntBits(
            other.getVy()));
    result = result && (
        java.lang.Float.floatToIntBits(getVz())
        == java.lang.Float.floatToIntBits(
            other.getVz()));
    result = result && (
        java.lang.Float.floatToIntBits(getMass())
        == java.lang.Float.floatToIntBits(
            other.getMass()));
    result = result && (
        java.lang.Float.floatToIntBits(getRadius())
        == java.lang.Float.floatToIntBits(
            other.getRadius()));
    result = result && (getIsSun()
        == other.getIsSun());
    result = result && collisionBehavior_ == other.collisionBehavior_;
    result = result && bodyColor_ == other.bodyColor_;
    result = result && (
        java.lang.Float.floatToIntBits(getFragFactor())
        == java.lang.Float.floatToIntBits(
            other.getFragFactor()));
    result = result && (
        java.lang.Float.floatToIntBits(getFragStep())
        == java.lang.Float.floatToIntBits(
            other.getFragStep()));
    result = result && (getWithTelemetry()
        == other.getWithTelemetry());
    result = result && getName()
        .equals(other.getName());
    result = result && getClass_()
        .equals(other.getClass_());
    result = result && (getPinned()
        == other.getPinned());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + X_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getX());
    hash = (37 * hash) + Y_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getY());
    hash = (37 * hash) + Z_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getZ());
    hash = (37 * hash) + VX_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getVx());
    hash = (37 * hash) + VY_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getVy());
    hash = (37 * hash) + VZ_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getVz());
    hash = (37 * hash) + MASS_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getMass());
    hash = (37 * hash) + RADIUS_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getRadius());
    hash = (37 * hash) + IS_SUN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsSun());
    hash = (37 * hash) + COLLISION_BEHAVIOR_FIELD_NUMBER;
    hash = (53 * hash) + collisionBehavior_;
    hash = (37 * hash) + BODY_COLOR_FIELD_NUMBER;
    hash = (53 * hash) + bodyColor_;
    hash = (37 * hash) + FRAG_FACTOR_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getFragFactor());
    hash = (37 * hash) + FRAG_STEP_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getFragStep());
    hash = (37 * hash) + WITH_TELEMETRY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getWithTelemetry());
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + CLASS_FIELD_NUMBER;
    hash = (53 * hash) + getClass_().hashCode();
    hash = (37 * hash) + PINNED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getPinned());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.ericace.grpcserver.BodyDescription parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ericace.grpcserver.BodyDescription parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ericace.grpcserver.BodyDescription parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ericace.grpcserver.BodyDescription parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ericace.grpcserver.BodyDescription parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.ericace.grpcserver.BodyDescription parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.ericace.grpcserver.BodyDescription parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.ericace.grpcserver.BodyDescription parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.ericace.grpcserver.BodyDescription parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.ericace.grpcserver.BodyDescription parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.ericace.grpcserver.BodyDescription prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * All the params required to represent a body in the simulation
   * </pre>
   *
   * Protobuf type {@code nbodyservice.BodyDescription}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nbodyservice.BodyDescription)
      org.ericace.grpcserver.BodyDescriptionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ericace.grpcserver.Nbodyservice.internal_static_nbodyservice_BodyDescription_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ericace.grpcserver.Nbodyservice.internal_static_nbodyservice_BodyDescription_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.ericace.grpcserver.BodyDescription.class, org.ericace.grpcserver.BodyDescription.Builder.class);
    }

    // Construct using org.ericace.grpcserver.BodyDescription.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      x_ = 0F;

      y_ = 0F;

      z_ = 0F;

      vx_ = 0F;

      vy_ = 0F;

      vz_ = 0F;

      mass_ = 0F;

      radius_ = 0F;

      isSun_ = false;

      collisionBehavior_ = 0;

      bodyColor_ = 0;

      fragFactor_ = 0F;

      fragStep_ = 0F;

      withTelemetry_ = false;

      name_ = "";

      class__ = "";

      pinned_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.ericace.grpcserver.Nbodyservice.internal_static_nbodyservice_BodyDescription_descriptor;
    }

    public org.ericace.grpcserver.BodyDescription getDefaultInstanceForType() {
      return org.ericace.grpcserver.BodyDescription.getDefaultInstance();
    }

    public org.ericace.grpcserver.BodyDescription build() {
      org.ericace.grpcserver.BodyDescription result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.ericace.grpcserver.BodyDescription buildPartial() {
      org.ericace.grpcserver.BodyDescription result = new org.ericace.grpcserver.BodyDescription(this);
      result.x_ = x_;
      result.y_ = y_;
      result.z_ = z_;
      result.vx_ = vx_;
      result.vy_ = vy_;
      result.vz_ = vz_;
      result.mass_ = mass_;
      result.radius_ = radius_;
      result.isSun_ = isSun_;
      result.collisionBehavior_ = collisionBehavior_;
      result.bodyColor_ = bodyColor_;
      result.fragFactor_ = fragFactor_;
      result.fragStep_ = fragStep_;
      result.withTelemetry_ = withTelemetry_;
      result.name_ = name_;
      result.class__ = class__;
      result.pinned_ = pinned_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.ericace.grpcserver.BodyDescription) {
        return mergeFrom((org.ericace.grpcserver.BodyDescription)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.ericace.grpcserver.BodyDescription other) {
      if (other == org.ericace.grpcserver.BodyDescription.getDefaultInstance()) return this;
      if (other.getX() != 0F) {
        setX(other.getX());
      }
      if (other.getY() != 0F) {
        setY(other.getY());
      }
      if (other.getZ() != 0F) {
        setZ(other.getZ());
      }
      if (other.getVx() != 0F) {
        setVx(other.getVx());
      }
      if (other.getVy() != 0F) {
        setVy(other.getVy());
      }
      if (other.getVz() != 0F) {
        setVz(other.getVz());
      }
      if (other.getMass() != 0F) {
        setMass(other.getMass());
      }
      if (other.getRadius() != 0F) {
        setRadius(other.getRadius());
      }
      if (other.getIsSun() != false) {
        setIsSun(other.getIsSun());
      }
      if (other.collisionBehavior_ != 0) {
        setCollisionBehaviorValue(other.getCollisionBehaviorValue());
      }
      if (other.bodyColor_ != 0) {
        setBodyColorValue(other.getBodyColorValue());
      }
      if (other.getFragFactor() != 0F) {
        setFragFactor(other.getFragFactor());
      }
      if (other.getFragStep() != 0F) {
        setFragStep(other.getFragStep());
      }
      if (other.getWithTelemetry() != false) {
        setWithTelemetry(other.getWithTelemetry());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getClass_().isEmpty()) {
        class__ = other.class__;
        onChanged();
      }
      if (other.getPinned() != false) {
        setPinned(other.getPinned());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.ericace.grpcserver.BodyDescription parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.ericace.grpcserver.BodyDescription) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private float x_ ;
    /**
     * <code>optional float x = 1;</code>
     */
    public float getX() {
      return x_;
    }
    /**
     * <code>optional float x = 1;</code>
     */
    public Builder setX(float value) {
      
      x_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float x = 1;</code>
     */
    public Builder clearX() {
      
      x_ = 0F;
      onChanged();
      return this;
    }

    private float y_ ;
    /**
     * <code>optional float y = 2;</code>
     */
    public float getY() {
      return y_;
    }
    /**
     * <code>optional float y = 2;</code>
     */
    public Builder setY(float value) {
      
      y_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float y = 2;</code>
     */
    public Builder clearY() {
      
      y_ = 0F;
      onChanged();
      return this;
    }

    private float z_ ;
    /**
     * <code>optional float z = 3;</code>
     */
    public float getZ() {
      return z_;
    }
    /**
     * <code>optional float z = 3;</code>
     */
    public Builder setZ(float value) {
      
      z_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float z = 3;</code>
     */
    public Builder clearZ() {
      
      z_ = 0F;
      onChanged();
      return this;
    }

    private float vx_ ;
    /**
     * <code>optional float vx = 4;</code>
     */
    public float getVx() {
      return vx_;
    }
    /**
     * <code>optional float vx = 4;</code>
     */
    public Builder setVx(float value) {
      
      vx_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float vx = 4;</code>
     */
    public Builder clearVx() {
      
      vx_ = 0F;
      onChanged();
      return this;
    }

    private float vy_ ;
    /**
     * <code>optional float vy = 5;</code>
     */
    public float getVy() {
      return vy_;
    }
    /**
     * <code>optional float vy = 5;</code>
     */
    public Builder setVy(float value) {
      
      vy_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float vy = 5;</code>
     */
    public Builder clearVy() {
      
      vy_ = 0F;
      onChanged();
      return this;
    }

    private float vz_ ;
    /**
     * <code>optional float vz = 6;</code>
     */
    public float getVz() {
      return vz_;
    }
    /**
     * <code>optional float vz = 6;</code>
     */
    public Builder setVz(float value) {
      
      vz_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float vz = 6;</code>
     */
    public Builder clearVz() {
      
      vz_ = 0F;
      onChanged();
      return this;
    }

    private float mass_ ;
    /**
     * <code>optional float mass = 7;</code>
     */
    public float getMass() {
      return mass_;
    }
    /**
     * <code>optional float mass = 7;</code>
     */
    public Builder setMass(float value) {
      
      mass_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float mass = 7;</code>
     */
    public Builder clearMass() {
      
      mass_ = 0F;
      onChanged();
      return this;
    }

    private float radius_ ;
    /**
     * <code>optional float radius = 8;</code>
     */
    public float getRadius() {
      return radius_;
    }
    /**
     * <code>optional float radius = 8;</code>
     */
    public Builder setRadius(float value) {
      
      radius_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float radius = 8;</code>
     */
    public Builder clearRadius() {
      
      radius_ = 0F;
      onChanged();
      return this;
    }

    private boolean isSun_ ;
    /**
     * <code>optional bool is_sun = 9;</code>
     */
    public boolean getIsSun() {
      return isSun_;
    }
    /**
     * <code>optional bool is_sun = 9;</code>
     */
    public Builder setIsSun(boolean value) {
      
      isSun_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool is_sun = 9;</code>
     */
    public Builder clearIsSun() {
      
      isSun_ = false;
      onChanged();
      return this;
    }

    private int collisionBehavior_ = 0;
    /**
     * <code>optional .nbodyservice.CollisionBehaviorEnum collision_behavior = 10;</code>
     */
    public int getCollisionBehaviorValue() {
      return collisionBehavior_;
    }
    /**
     * <code>optional .nbodyservice.CollisionBehaviorEnum collision_behavior = 10;</code>
     */
    public Builder setCollisionBehaviorValue(int value) {
      collisionBehavior_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .nbodyservice.CollisionBehaviorEnum collision_behavior = 10;</code>
     */
    public org.ericace.grpcserver.CollisionBehaviorEnum getCollisionBehavior() {
      org.ericace.grpcserver.CollisionBehaviorEnum result = org.ericace.grpcserver.CollisionBehaviorEnum.valueOf(collisionBehavior_);
      return result == null ? org.ericace.grpcserver.CollisionBehaviorEnum.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .nbodyservice.CollisionBehaviorEnum collision_behavior = 10;</code>
     */
    public Builder setCollisionBehavior(org.ericace.grpcserver.CollisionBehaviorEnum value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      collisionBehavior_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .nbodyservice.CollisionBehaviorEnum collision_behavior = 10;</code>
     */
    public Builder clearCollisionBehavior() {
      
      collisionBehavior_ = 0;
      onChanged();
      return this;
    }

    private int bodyColor_ = 0;
    /**
     * <code>optional .nbodyservice.BodyColorEnum body_color = 11;</code>
     */
    public int getBodyColorValue() {
      return bodyColor_;
    }
    /**
     * <code>optional .nbodyservice.BodyColorEnum body_color = 11;</code>
     */
    public Builder setBodyColorValue(int value) {
      bodyColor_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .nbodyservice.BodyColorEnum body_color = 11;</code>
     */
    public org.ericace.grpcserver.BodyColorEnum getBodyColor() {
      org.ericace.grpcserver.BodyColorEnum result = org.ericace.grpcserver.BodyColorEnum.valueOf(bodyColor_);
      return result == null ? org.ericace.grpcserver.BodyColorEnum.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .nbodyservice.BodyColorEnum body_color = 11;</code>
     */
    public Builder setBodyColor(org.ericace.grpcserver.BodyColorEnum value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      bodyColor_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .nbodyservice.BodyColorEnum body_color = 11;</code>
     */
    public Builder clearBodyColor() {
      
      bodyColor_ = 0;
      onChanged();
      return this;
    }

    private float fragFactor_ ;
    /**
     * <code>optional float frag_factor = 12;</code>
     */
    public float getFragFactor() {
      return fragFactor_;
    }
    /**
     * <code>optional float frag_factor = 12;</code>
     */
    public Builder setFragFactor(float value) {
      
      fragFactor_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float frag_factor = 12;</code>
     */
    public Builder clearFragFactor() {
      
      fragFactor_ = 0F;
      onChanged();
      return this;
    }

    private float fragStep_ ;
    /**
     * <code>optional float frag_step = 13;</code>
     */
    public float getFragStep() {
      return fragStep_;
    }
    /**
     * <code>optional float frag_step = 13;</code>
     */
    public Builder setFragStep(float value) {
      
      fragStep_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float frag_step = 13;</code>
     */
    public Builder clearFragStep() {
      
      fragStep_ = 0F;
      onChanged();
      return this;
    }

    private boolean withTelemetry_ ;
    /**
     * <code>optional bool with_telemetry = 14;</code>
     */
    public boolean getWithTelemetry() {
      return withTelemetry_;
    }
    /**
     * <code>optional bool with_telemetry = 14;</code>
     */
    public Builder setWithTelemetry(boolean value) {
      
      withTelemetry_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool with_telemetry = 14;</code>
     */
    public Builder clearWithTelemetry() {
      
      withTelemetry_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>optional string name = 15;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string name = 15;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string name = 15;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 15;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 15;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object class__ = "";
    /**
     * <code>optional string class = 16;</code>
     */
    public java.lang.String getClass_() {
      java.lang.Object ref = class__;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        class__ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string class = 16;</code>
     */
    public com.google.protobuf.ByteString
        getClass_Bytes() {
      java.lang.Object ref = class__;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        class__ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string class = 16;</code>
     */
    public Builder setClass_(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      class__ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string class = 16;</code>
     */
    public Builder clearClass_() {
      
      class__ = getDefaultInstance().getClass_();
      onChanged();
      return this;
    }
    /**
     * <code>optional string class = 16;</code>
     */
    public Builder setClass_Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      class__ = value;
      onChanged();
      return this;
    }

    private boolean pinned_ ;
    /**
     * <code>optional bool pinned = 17;</code>
     */
    public boolean getPinned() {
      return pinned_;
    }
    /**
     * <code>optional bool pinned = 17;</code>
     */
    public Builder setPinned(boolean value) {
      
      pinned_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool pinned = 17;</code>
     */
    public Builder clearPinned() {
      
      pinned_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:nbodyservice.BodyDescription)
  }

  // @@protoc_insertion_point(class_scope:nbodyservice.BodyDescription)
  private static final org.ericace.grpcserver.BodyDescription DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.ericace.grpcserver.BodyDescription();
  }

  public static org.ericace.grpcserver.BodyDescription getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BodyDescription>
      PARSER = new com.google.protobuf.AbstractParser<BodyDescription>() {
    public BodyDescription parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new BodyDescription(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BodyDescription> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BodyDescription> getParserForType() {
    return PARSER;
  }

  public org.ericace.grpcserver.BodyDescription getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

