// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nbodyservice.proto

package org.ericace.grpcserver;

/**
 * Protobuf enum {@code nbodyservice.CollisionBehaviorEnum}
 */
public enum CollisionBehaviorEnum
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNDEF = 0;</code>
   */
  UNDEF(0),
  /**
   * <code>NONE = 1;</code>
   */
  NONE(1),
  /**
   * <code>SUBSUME = 2;</code>
   */
  SUBSUME(2),
  /**
   * <code>ELASTIC = 3;</code>
   */
  ELASTIC(3),
  /**
   * <code>FRAGMENT = 4;</code>
   */
  FRAGMENT(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNDEF = 0;</code>
   */
  public static final int UNDEF_VALUE = 0;
  /**
   * <code>NONE = 1;</code>
   */
  public static final int NONE_VALUE = 1;
  /**
   * <code>SUBSUME = 2;</code>
   */
  public static final int SUBSUME_VALUE = 2;
  /**
   * <code>ELASTIC = 3;</code>
   */
  public static final int ELASTIC_VALUE = 3;
  /**
   * <code>FRAGMENT = 4;</code>
   */
  public static final int FRAGMENT_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static CollisionBehaviorEnum valueOf(int value) {
    return forNumber(value);
  }

  public static CollisionBehaviorEnum forNumber(int value) {
    switch (value) {
      case 0: return UNDEF;
      case 1: return NONE;
      case 2: return SUBSUME;
      case 3: return ELASTIC;
      case 4: return FRAGMENT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<CollisionBehaviorEnum>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      CollisionBehaviorEnum> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<CollisionBehaviorEnum>() {
          public CollisionBehaviorEnum findValueByNumber(int number) {
            return CollisionBehaviorEnum.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.ericace.grpcserver.Nbodyservice.getDescriptor()
        .getEnumTypes().get(0);
  }

  private static final CollisionBehaviorEnum[] VALUES = values();

  public static CollisionBehaviorEnum valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private CollisionBehaviorEnum(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:nbodyservice.CollisionBehaviorEnum)
}

