// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nbodyservice.proto

package org.ericace.grpcserver;

/**
 * <pre>
 * Holds the values of configurables
 * </pre>
 *
 * Protobuf type {@code nbodyservice.CurrentConfig}
 */
public  final class CurrentConfig extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:nbodyservice.CurrentConfig)
    CurrentConfigOrBuilder {
  // Use CurrentConfig.newBuilder() to construct.
  private CurrentConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CurrentConfig() {
    bodies_ = 0L;
    resultQueueSize_ = 0L;
    computationThreads_ = 0L;
    smoothingFactor_ = 0F;
    restitutionCoefficient_ = 0F;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private CurrentConfig(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            bodies_ = input.readInt64();
            break;
          }
          case 16: {

            resultQueueSize_ = input.readInt64();
            break;
          }
          case 24: {

            computationThreads_ = input.readInt64();
            break;
          }
          case 37: {

            smoothingFactor_ = input.readFloat();
            break;
          }
          case 53: {

            restitutionCoefficient_ = input.readFloat();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.ericace.grpcserver.Nbodyservice.internal_static_nbodyservice_CurrentConfig_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.ericace.grpcserver.Nbodyservice.internal_static_nbodyservice_CurrentConfig_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.ericace.grpcserver.CurrentConfig.class, org.ericace.grpcserver.CurrentConfig.Builder.class);
  }

  public static final int BODIES_FIELD_NUMBER = 1;
  private long bodies_;
  /**
   * <code>optional int64 bodies = 1;</code>
   */
  public long getBodies() {
    return bodies_;
  }

  public static final int RESULT_QUEUE_SIZE_FIELD_NUMBER = 2;
  private long resultQueueSize_;
  /**
   * <code>optional int64 result_queue_size = 2;</code>
   */
  public long getResultQueueSize() {
    return resultQueueSize_;
  }

  public static final int COMPUTATION_THREADS_FIELD_NUMBER = 3;
  private long computationThreads_;
  /**
   * <code>optional int64 computation_threads = 3;</code>
   */
  public long getComputationThreads() {
    return computationThreads_;
  }

  public static final int SMOOTHING_FACTOR_FIELD_NUMBER = 4;
  private float smoothingFactor_;
  /**
   * <code>optional float smoothing_factor = 4;</code>
   */
  public float getSmoothingFactor() {
    return smoothingFactor_;
  }

  public static final int RESTITUTION_COEFFICIENT_FIELD_NUMBER = 6;
  private float restitutionCoefficient_;
  /**
   * <code>optional float restitution_coefficient = 6;</code>
   */
  public float getRestitutionCoefficient() {
    return restitutionCoefficient_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (bodies_ != 0L) {
      output.writeInt64(1, bodies_);
    }
    if (resultQueueSize_ != 0L) {
      output.writeInt64(2, resultQueueSize_);
    }
    if (computationThreads_ != 0L) {
      output.writeInt64(3, computationThreads_);
    }
    if (smoothingFactor_ != 0F) {
      output.writeFloat(4, smoothingFactor_);
    }
    if (restitutionCoefficient_ != 0F) {
      output.writeFloat(6, restitutionCoefficient_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (bodies_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, bodies_);
    }
    if (resultQueueSize_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, resultQueueSize_);
    }
    if (computationThreads_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, computationThreads_);
    }
    if (smoothingFactor_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(4, smoothingFactor_);
    }
    if (restitutionCoefficient_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(6, restitutionCoefficient_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.ericace.grpcserver.CurrentConfig)) {
      return super.equals(obj);
    }
    org.ericace.grpcserver.CurrentConfig other = (org.ericace.grpcserver.CurrentConfig) obj;

    boolean result = true;
    result = result && (getBodies()
        == other.getBodies());
    result = result && (getResultQueueSize()
        == other.getResultQueueSize());
    result = result && (getComputationThreads()
        == other.getComputationThreads());
    result = result && (
        java.lang.Float.floatToIntBits(getSmoothingFactor())
        == java.lang.Float.floatToIntBits(
            other.getSmoothingFactor()));
    result = result && (
        java.lang.Float.floatToIntBits(getRestitutionCoefficient())
        == java.lang.Float.floatToIntBits(
            other.getRestitutionCoefficient()));
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + BODIES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBodies());
    hash = (37 * hash) + RESULT_QUEUE_SIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getResultQueueSize());
    hash = (37 * hash) + COMPUTATION_THREADS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getComputationThreads());
    hash = (37 * hash) + SMOOTHING_FACTOR_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getSmoothingFactor());
    hash = (37 * hash) + RESTITUTION_COEFFICIENT_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getRestitutionCoefficient());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.ericace.grpcserver.CurrentConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ericace.grpcserver.CurrentConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ericace.grpcserver.CurrentConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ericace.grpcserver.CurrentConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ericace.grpcserver.CurrentConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.ericace.grpcserver.CurrentConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.ericace.grpcserver.CurrentConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.ericace.grpcserver.CurrentConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.ericace.grpcserver.CurrentConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.ericace.grpcserver.CurrentConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.ericace.grpcserver.CurrentConfig prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Holds the values of configurables
   * </pre>
   *
   * Protobuf type {@code nbodyservice.CurrentConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nbodyservice.CurrentConfig)
      org.ericace.grpcserver.CurrentConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ericace.grpcserver.Nbodyservice.internal_static_nbodyservice_CurrentConfig_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ericace.grpcserver.Nbodyservice.internal_static_nbodyservice_CurrentConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.ericace.grpcserver.CurrentConfig.class, org.ericace.grpcserver.CurrentConfig.Builder.class);
    }

    // Construct using org.ericace.grpcserver.CurrentConfig.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      bodies_ = 0L;

      resultQueueSize_ = 0L;

      computationThreads_ = 0L;

      smoothingFactor_ = 0F;

      restitutionCoefficient_ = 0F;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.ericace.grpcserver.Nbodyservice.internal_static_nbodyservice_CurrentConfig_descriptor;
    }

    public org.ericace.grpcserver.CurrentConfig getDefaultInstanceForType() {
      return org.ericace.grpcserver.CurrentConfig.getDefaultInstance();
    }

    public org.ericace.grpcserver.CurrentConfig build() {
      org.ericace.grpcserver.CurrentConfig result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.ericace.grpcserver.CurrentConfig buildPartial() {
      org.ericace.grpcserver.CurrentConfig result = new org.ericace.grpcserver.CurrentConfig(this);
      result.bodies_ = bodies_;
      result.resultQueueSize_ = resultQueueSize_;
      result.computationThreads_ = computationThreads_;
      result.smoothingFactor_ = smoothingFactor_;
      result.restitutionCoefficient_ = restitutionCoefficient_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.ericace.grpcserver.CurrentConfig) {
        return mergeFrom((org.ericace.grpcserver.CurrentConfig)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.ericace.grpcserver.CurrentConfig other) {
      if (other == org.ericace.grpcserver.CurrentConfig.getDefaultInstance()) return this;
      if (other.getBodies() != 0L) {
        setBodies(other.getBodies());
      }
      if (other.getResultQueueSize() != 0L) {
        setResultQueueSize(other.getResultQueueSize());
      }
      if (other.getComputationThreads() != 0L) {
        setComputationThreads(other.getComputationThreads());
      }
      if (other.getSmoothingFactor() != 0F) {
        setSmoothingFactor(other.getSmoothingFactor());
      }
      if (other.getRestitutionCoefficient() != 0F) {
        setRestitutionCoefficient(other.getRestitutionCoefficient());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.ericace.grpcserver.CurrentConfig parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.ericace.grpcserver.CurrentConfig) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long bodies_ ;
    /**
     * <code>optional int64 bodies = 1;</code>
     */
    public long getBodies() {
      return bodies_;
    }
    /**
     * <code>optional int64 bodies = 1;</code>
     */
    public Builder setBodies(long value) {
      
      bodies_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 bodies = 1;</code>
     */
    public Builder clearBodies() {
      
      bodies_ = 0L;
      onChanged();
      return this;
    }

    private long resultQueueSize_ ;
    /**
     * <code>optional int64 result_queue_size = 2;</code>
     */
    public long getResultQueueSize() {
      return resultQueueSize_;
    }
    /**
     * <code>optional int64 result_queue_size = 2;</code>
     */
    public Builder setResultQueueSize(long value) {
      
      resultQueueSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 result_queue_size = 2;</code>
     */
    public Builder clearResultQueueSize() {
      
      resultQueueSize_ = 0L;
      onChanged();
      return this;
    }

    private long computationThreads_ ;
    /**
     * <code>optional int64 computation_threads = 3;</code>
     */
    public long getComputationThreads() {
      return computationThreads_;
    }
    /**
     * <code>optional int64 computation_threads = 3;</code>
     */
    public Builder setComputationThreads(long value) {
      
      computationThreads_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 computation_threads = 3;</code>
     */
    public Builder clearComputationThreads() {
      
      computationThreads_ = 0L;
      onChanged();
      return this;
    }

    private float smoothingFactor_ ;
    /**
     * <code>optional float smoothing_factor = 4;</code>
     */
    public float getSmoothingFactor() {
      return smoothingFactor_;
    }
    /**
     * <code>optional float smoothing_factor = 4;</code>
     */
    public Builder setSmoothingFactor(float value) {
      
      smoothingFactor_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float smoothing_factor = 4;</code>
     */
    public Builder clearSmoothingFactor() {
      
      smoothingFactor_ = 0F;
      onChanged();
      return this;
    }

    private float restitutionCoefficient_ ;
    /**
     * <code>optional float restitution_coefficient = 6;</code>
     */
    public float getRestitutionCoefficient() {
      return restitutionCoefficient_;
    }
    /**
     * <code>optional float restitution_coefficient = 6;</code>
     */
    public Builder setRestitutionCoefficient(float value) {
      
      restitutionCoefficient_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float restitution_coefficient = 6;</code>
     */
    public Builder clearRestitutionCoefficient() {
      
      restitutionCoefficient_ = 0F;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:nbodyservice.CurrentConfig)
  }

  // @@protoc_insertion_point(class_scope:nbodyservice.CurrentConfig)
  private static final org.ericace.grpcserver.CurrentConfig DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.ericace.grpcserver.CurrentConfig();
  }

  public static org.ericace.grpcserver.CurrentConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CurrentConfig>
      PARSER = new com.google.protobuf.AbstractParser<CurrentConfig>() {
    public CurrentConfig parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new CurrentConfig(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CurrentConfig> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CurrentConfig> getParserForType() {
    return PARSER;
  }

  public org.ericace.grpcserver.CurrentConfig getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

