// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nbodyservice.proto

package org.ericace.grpcserver;

public interface CurrentConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nbodyservice.CurrentConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 bodies = 1;</code>
   */
  long getBodies();

  /**
   * <code>optional int64 result_queue_size = 2;</code>
   */
  long getResultQueueSize();

  /**
   * <code>optional int64 computation_threads = 3;</code>
   */
  long getComputationThreads();

  /**
   * <code>optional float smoothing_factor = 4;</code>
   */
  float getSmoothingFactor();

  /**
   * <code>optional float restitution_coefficient = 6;</code>
   */
  float getRestitutionCoefficient();
}
