// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nbodyservice.proto

package org.ericace.grpcserver;

public interface FactorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nbodyservice.Factor)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional float factor = 1;</code>
   */
  float getFactor();
}
