// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nbodyservice.proto

package org.ericace.grpcserver;

public interface ItemCountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nbodyservice.ItemCount)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 item_count = 1;</code>
   */
  long getItemCount();
}
