// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nbodyservice.proto

package org.ericace.grpcserver;

public interface ModBodyMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nbodyservice.ModBodyMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>optional string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string class = 3;</code>
   */
  java.lang.String getClass_();
  /**
   * <code>optional string class = 3;</code>
   */
  com.google.protobuf.ByteString
      getClass_Bytes();

  /**
   * <code>repeated string p = 4;</code>
   */
  java.util.List<java.lang.String>
      getPList();
  /**
   * <code>repeated string p = 4;</code>
   */
  int getPCount();
  /**
   * <code>repeated string p = 4;</code>
   */
  java.lang.String getP(int index);
  /**
   * <code>repeated string p = 4;</code>
   */
  com.google.protobuf.ByteString
      getPBytes(int index);
}
