// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nbodyservice.proto

package org.ericace.grpcserver;

/**
 * <pre>
 * Modify body properties. To modify by ID, pass the ID and omit name and class:
 *   ModBody "id: 1 p: 'radius=100'"
 * To modify by name or class, pass the ID as -1, and provide name or class:
 *   ModBody "id: -1 name='jupiter' p: 'radius=100'"
 * ID has to be passed in this case because the cli tool (or the protobuf protocol) passes a non-specified
 * int field as zero, which happens to be a valid body ID pretty much all the time...
 * Pass an array of params via the cli by repeating the 'p' message:
 *   ModBody "id: 1 p: 'radius=100' p: 'vx=200' p: 'collision=NONE'"
 * </pre>
 *
 * Protobuf type {@code nbodyservice.ModBodyMessage}
 */
public  final class ModBodyMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:nbodyservice.ModBodyMessage)
    ModBodyMessageOrBuilder {
  // Use ModBodyMessage.newBuilder() to construct.
  private ModBodyMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ModBodyMessage() {
    id_ = 0L;
    name_ = "";
    class__ = "";
    p_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ModBodyMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            class__ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              p_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000008;
            }
            p_.add(s);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        p_ = p_.getUnmodifiableView();
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.ericace.grpcserver.Nbodyservice.internal_static_nbodyservice_ModBodyMessage_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.ericace.grpcserver.Nbodyservice.internal_static_nbodyservice_ModBodyMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.ericace.grpcserver.ModBodyMessage.class, org.ericace.grpcserver.ModBodyMessage.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>optional int64 id = 1;</code>
   */
  public long getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>optional string name = 2;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>optional string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLASS_FIELD_NUMBER = 3;
  private volatile java.lang.Object class__;
  /**
   * <code>optional string class = 3;</code>
   */
  public java.lang.String getClass_() {
    java.lang.Object ref = class__;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      class__ = s;
      return s;
    }
  }
  /**
   * <code>optional string class = 3;</code>
   */
  public com.google.protobuf.ByteString
      getClass_Bytes() {
    java.lang.Object ref = class__;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      class__ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int P_FIELD_NUMBER = 4;
  private com.google.protobuf.LazyStringList p_;
  /**
   * <code>repeated string p = 4;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getPList() {
    return p_;
  }
  /**
   * <code>repeated string p = 4;</code>
   */
  public int getPCount() {
    return p_.size();
  }
  /**
   * <code>repeated string p = 4;</code>
   */
  public java.lang.String getP(int index) {
    return p_.get(index);
  }
  /**
   * <code>repeated string p = 4;</code>
   */
  public com.google.protobuf.ByteString
      getPBytes(int index) {
    return p_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!getClass_Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, class__);
    }
    for (int i = 0; i < p_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, p_.getRaw(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!getClass_Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, class__);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < p_.size(); i++) {
        dataSize += computeStringSizeNoTag(p_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getPList().size();
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.ericace.grpcserver.ModBodyMessage)) {
      return super.equals(obj);
    }
    org.ericace.grpcserver.ModBodyMessage other = (org.ericace.grpcserver.ModBodyMessage) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && getName()
        .equals(other.getName());
    result = result && getClass_()
        .equals(other.getClass_());
    result = result && getPList()
        .equals(other.getPList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + CLASS_FIELD_NUMBER;
    hash = (53 * hash) + getClass_().hashCode();
    if (getPCount() > 0) {
      hash = (37 * hash) + P_FIELD_NUMBER;
      hash = (53 * hash) + getPList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.ericace.grpcserver.ModBodyMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ericace.grpcserver.ModBodyMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ericace.grpcserver.ModBodyMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ericace.grpcserver.ModBodyMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ericace.grpcserver.ModBodyMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.ericace.grpcserver.ModBodyMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.ericace.grpcserver.ModBodyMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.ericace.grpcserver.ModBodyMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.ericace.grpcserver.ModBodyMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.ericace.grpcserver.ModBodyMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.ericace.grpcserver.ModBodyMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Modify body properties. To modify by ID, pass the ID and omit name and class:
   *   ModBody "id: 1 p: 'radius=100'"
   * To modify by name or class, pass the ID as -1, and provide name or class:
   *   ModBody "id: -1 name='jupiter' p: 'radius=100'"
   * ID has to be passed in this case because the cli tool (or the protobuf protocol) passes a non-specified
   * int field as zero, which happens to be a valid body ID pretty much all the time...
   * Pass an array of params via the cli by repeating the 'p' message:
   *   ModBody "id: 1 p: 'radius=100' p: 'vx=200' p: 'collision=NONE'"
   * </pre>
   *
   * Protobuf type {@code nbodyservice.ModBodyMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nbodyservice.ModBodyMessage)
      org.ericace.grpcserver.ModBodyMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ericace.grpcserver.Nbodyservice.internal_static_nbodyservice_ModBodyMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ericace.grpcserver.Nbodyservice.internal_static_nbodyservice_ModBodyMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.ericace.grpcserver.ModBodyMessage.class, org.ericace.grpcserver.ModBodyMessage.Builder.class);
    }

    // Construct using org.ericace.grpcserver.ModBodyMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0L;

      name_ = "";

      class__ = "";

      p_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.ericace.grpcserver.Nbodyservice.internal_static_nbodyservice_ModBodyMessage_descriptor;
    }

    public org.ericace.grpcserver.ModBodyMessage getDefaultInstanceForType() {
      return org.ericace.grpcserver.ModBodyMessage.getDefaultInstance();
    }

    public org.ericace.grpcserver.ModBodyMessage build() {
      org.ericace.grpcserver.ModBodyMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.ericace.grpcserver.ModBodyMessage buildPartial() {
      org.ericace.grpcserver.ModBodyMessage result = new org.ericace.grpcserver.ModBodyMessage(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.id_ = id_;
      result.name_ = name_;
      result.class__ = class__;
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        p_ = p_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000008);
      }
      result.p_ = p_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.ericace.grpcserver.ModBodyMessage) {
        return mergeFrom((org.ericace.grpcserver.ModBodyMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.ericace.grpcserver.ModBodyMessage other) {
      if (other == org.ericace.grpcserver.ModBodyMessage.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getClass_().isEmpty()) {
        class__ = other.class__;
        onChanged();
      }
      if (!other.p_.isEmpty()) {
        if (p_.isEmpty()) {
          p_ = other.p_;
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          ensurePIsMutable();
          p_.addAll(other.p_);
        }
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.ericace.grpcserver.ModBodyMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.ericace.grpcserver.ModBodyMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>optional int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>optional int64 id = 1;</code>
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object class__ = "";
    /**
     * <code>optional string class = 3;</code>
     */
    public java.lang.String getClass_() {
      java.lang.Object ref = class__;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        class__ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string class = 3;</code>
     */
    public com.google.protobuf.ByteString
        getClass_Bytes() {
      java.lang.Object ref = class__;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        class__ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string class = 3;</code>
     */
    public Builder setClass_(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      class__ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string class = 3;</code>
     */
    public Builder clearClass_() {
      
      class__ = getDefaultInstance().getClass_();
      onChanged();
      return this;
    }
    /**
     * <code>optional string class = 3;</code>
     */
    public Builder setClass_Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      class__ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList p_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensurePIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        p_ = new com.google.protobuf.LazyStringArrayList(p_);
        bitField0_ |= 0x00000008;
       }
    }
    /**
     * <code>repeated string p = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getPList() {
      return p_.getUnmodifiableView();
    }
    /**
     * <code>repeated string p = 4;</code>
     */
    public int getPCount() {
      return p_.size();
    }
    /**
     * <code>repeated string p = 4;</code>
     */
    public java.lang.String getP(int index) {
      return p_.get(index);
    }
    /**
     * <code>repeated string p = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPBytes(int index) {
      return p_.getByteString(index);
    }
    /**
     * <code>repeated string p = 4;</code>
     */
    public Builder setP(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePIsMutable();
      p_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string p = 4;</code>
     */
    public Builder addP(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePIsMutable();
      p_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string p = 4;</code>
     */
    public Builder addAllP(
        java.lang.Iterable<java.lang.String> values) {
      ensurePIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, p_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string p = 4;</code>
     */
    public Builder clearP() {
      p_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string p = 4;</code>
     */
    public Builder addPBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensurePIsMutable();
      p_.add(value);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:nbodyservice.ModBodyMessage)
  }

  // @@protoc_insertion_point(class_scope:nbodyservice.ModBodyMessage)
  private static final org.ericace.grpcserver.ModBodyMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.ericace.grpcserver.ModBodyMessage();
  }

  public static org.ericace.grpcserver.ModBodyMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ModBodyMessage>
      PARSER = new com.google.protobuf.AbstractParser<ModBodyMessage>() {
    public ModBodyMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ModBodyMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ModBodyMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ModBodyMessage> getParserForType() {
    return PARSER;
  }

  public org.ericace.grpcserver.ModBodyMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

