// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nbodyservice.proto

package org.ericace.grpcserver;

public interface RestitutionCoefficientOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nbodyservice.RestitutionCoefficient)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional float restitution_coefficient = 1;</code>
   */
  float getRestitutionCoefficient();
}
