// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nbodyservice.proto

package org.ericace.grpcserver;

public interface ResultCodeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nbodyservice.ResultCode)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .nbodyservice.ResultCode.ResultCodeEnum result_code = 1;</code>
   */
  int getResultCodeValue();
  /**
   * <code>optional .nbodyservice.ResultCode.ResultCodeEnum result_code = 1;</code>
   */
  org.ericace.grpcserver.ResultCode.ResultCodeEnum getResultCode();

  /**
   * <code>optional string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
